
infrastructure:
  - name: web-server
    provider: aws
    type: ec2
    instance_type: t3.micro
    region: us-east-1

  - name: db-server
    provider: gcp
    type: compute
    instance_type: e2-medium
    region: us-central1

  - name: cache
    provider: aws
    type: elasticache
    instance_type: cache.t3.small
    region: us-east-1

compute:
  instances:
    - name: "api"
      provider: "aws"
      region: "us-east-1"
      family: "m7g.large"
      count: 3
      base_hourly_rate: 0.096
      discounts:
        purchase: "savings_plan"   # on_demand|spot|reserved|savings_plan|cud
        commitment: "1y"           # none|1y|3y
        # Provide the real effective discount when available (preferred):
        effective_discount_pct: 0.32
        attributes:
          sp_type: "compute"       # example attribute for AWS SP
    
